# Generated by Django 3.1.1 on 2021-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_page_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
